//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ContratosTerminados
    {
        public int IDContrato { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string NumeroContrato { get; set; }
        public bool SurfRacks { get; set; }
        public bool Cajon { get; set; }
        public bool RtvSticker { get; set; }
        public bool RtvPapel { get; set; }
        public bool MarchamoSticker { get; set; }
        public bool MarchamoPapel { get; set; }
        public bool StickerPlaca { get; set; }
        public bool TituloPropiedad { get; set; }
        public byte[] FrontalVehiculos { get; set; }
        public byte[] TraseraVehiculos { get; set; }
        public byte[] IzquierdaVehiculos { get; set; }
        public byte[] DerechaVehiculos { get; set; }
        public string IDVehiculo { get; set; }
        public int IDKilometraje { get; set; }
    
        public virtual t_Contratos t_Contratos { get; set; }
        public virtual t_Kilometrajes t_Kilometrajes { get; set; }
        public IDictionary<string, Object> ExtendedProperties { set; get; }
    }
}
