//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FacturaDetallePago
    {
        public int IDFacturaDetallePago { get; set; }
        public int IDFactura { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public int IDTipoPago { get; set; }
        public string Referencia { get; set; }
        public decimal Monto { get; set; }
    
        public virtual t_Facturas t_Facturas { get; set; }
        public virtual t_TiposPago t_TiposPago { get; set; }
    }
}
