//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_GastosDetalle
    {
        public int IDGastoDetalle { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string DescripcionGasto { get; set; }
        public decimal MontoGasto { get; set; }
        public string NumeroFacturaGasto { get; set; }
        public byte[] Factura { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int IDGasto { get; set; }
    
        public virtual t_Gastos t_Gastos { get; set; }
    }
}
