//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Kilometrajes
    {
        public int IDKilometraje { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<int> KilometrajeInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> KilometrajeFinal { get; set; }
        public Nullable<int> KilometrajeReccorrido { get; set; }
        public int IDVehiculo { get; set; }
        public int IDReservacion { get; set; }
    
        public virtual t_Vehiculos t_Vehiculos { get; set; }
    }
}
