//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Pantallas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Pantallas()
        {
            this.t_RolesSistemaModuloPantalla = new HashSet<t_RolesSistemaModuloPantalla>();
        }
    
        public int IDPantalla { get; set; }
        public int IDSistema { get; set; }
        public int IDModulo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string NombrePantalla { get; set; }
    
        public virtual t_Modulos t_Modulos { get; set; }
        public virtual t_Sistemas t_Sistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_RolesSistemaModuloPantalla> t_RolesSistemaModuloPantalla { get; set; }
    }
}
