//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_RolesSistemaModuloPantalla
    {
        public int IDRolPantalla { get; set; }
        public int IDRol { get; set; }
        public int IDSistema { get; set; }
        public int IDModulo { get; set; }
        public int IDPantalla { get; set; }
    
        public virtual t_Pantallas t_Pantallas { get; set; }
        public virtual t_Roles t_Roles { get; set; }
    }
}
