//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViwolfRental.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Usuarios()
        {
            this.t_Reservaciones = new HashSet<t_Reservaciones>();
        }
    
        public int IdUsuario { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string NombreUsuario { get; set; }
        public string PrimerApellidoUsuario { get; set; }
        public string SegundoApellidoUsuario { get; set; }
        public string CodigoUsuario { get; set; }
        public string Password { get; set; }
        public int IdSistema { get; set; }
        public int IdRol { get; set; }
        public bool Activo { get; set; }
        public int IDDepartamento { get; set; }
    
        public virtual t_Departamentos t_Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Reservaciones> t_Reservaciones { get; set; }
        public virtual t_Roles t_Roles { get; set; }
        public virtual t_Sistemas t_Sistemas { get; set; }
    }
}
